trigger:
- main

variables:
  gkeCluster: 'proview-dev-gke'
  gkeZone: 'asia-southeast1'
  gkeProject: 'endless-elysium-402509'
  helmChartRepo: 'https://github.com/Shubham2194/ci-cd-demo.git'
  helmChartPath: 'nginx'
  helmReleaseName: 'nginx-release'
  namespace: 'backend'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: 'private-pool'
    steps:
      
    - script: |
        echo $$GCLOUD_SERVICE_KEY > gcloud-service-key.json
        gcloud auth activate-service-account --key-file=gcloud-service-key.json
        gcloud container clusters get-credentials $(gkeCluster) --zone $(gkeZone) --project $(gkeProject)
      displayName: 'Configure gcloud'
      env:
        GCLOUD_SERVICE_KEY: $(gcloudServiceConnection)    
   
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      name: 'private-pool'
      vmImage: 'ubuntu-latest'
   
    steps:
    - script: |
        git clone $(helmChartRepo) helm-chart
      displayName: 'Clone Helm Chart Repository'
    - script: |
        helm upgrade --install $(helmReleaseName) helm-chart/$(helmChartPath) --namespace $(namespace)
      displayName: 'Deploy Helm Chart'
